version: '3.9'

services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=widgets-api
      - POSTGRES_DB=widgets-api
  widgets-api:
    image: rimvydaspranciulis/widgets-api:latest
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/widgets-api