version: '3.9'

services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=widgets-api
      - POSTGRES_DB=widgets-api